<html>
<head>
    <title>Register page</title>
    <meta charset="utf-8">
    <link href='vendor/harvesthq/chosen/chosen.css' rel='stylesheet' type='text/css'>
    <link href='app/frontend/css/main.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <script type="text/javascript" src="vendor/components/jquery/jquery.js"></script>
    <script type="text/javascript" src="vendor/harvesthq/chosen/chosen.jquery.js"></script>
    <script type="text/javascript" src="vendor/robinherbots/jquery.inputmask/dist/jquery.inputmask.js"></script>
</head>
<body>

    <div> 
      <?require_once "templates/form.php"?>
    </div>

    <script type="text/javascript" src="app/frontend/js/main.js"></script>
</body>
</html>

