<div class="block-full-note">
	<div class="full-conc-btn-0"></div>
	<input class="full-note-title" placeholder="Title note">
	<div>
		<textarea class="full-main-note-text" placeholder="Your notes">
			<?=$text?>
		</textarea> 
	</div>
	<div class="full-btn-container">
		<button class="bth-full-note" id="save-full-btn">Save</button>
		<button class="bth-full-note" id="close-full-bth">Close</button>
	</div>
	<div class="error-container">
		<span class="errors error-full-note"></span>
	</div>
</div>
