<nav class="navigation-menu js-nav-menu">
        <div class="navigation-menu__toggle js-nav-menu-toggle">
            <span class="navigation-menu__bars"></span>
        </div>
        <ul class="menu-list">
            <h1 class="text-menu">MENU</h1>
            <li class="menu-list__item">
                <div class="button_cont" align="left">
                    <button class="menu-button" id="add-note" rel="nofollow noopener">
                        Add Note
                    </button>
                </div>
            </li>
            <li class="menu-list__item">
                <div class="button_cont" align="left">
                    <form method="POST">
                        <button type='submit' name="Log_Out" value="Log Out" class="menu-button" 
                                                                             id="log-out" 
                                                                             rel="nofollow noopener">
                           Log Out
                        </button>
                    </form>
                </div>
            </li>
        </ul>
    </nav>