<div class="popup-delete">
	<p>Are you sure to delete the entry?</p>
	<div class="container-buttons">
		<div class="button_cont" align="right">
			<button class="menu-button" id="yes-delete" rel="nofollow noopener">
               Yes
	    	</button>
	    </div>
		<div class="button_cont" align="left">
			<button class="menu-button" id="no-delete" rel="nofollow noopener">
               No
	    	</button>
	    </div>
	</div>
</div>